name: update weather

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Fetch and update weather data
        run: |
          TEMP=$(curl -s https://api.justinharing.nl/weather/Rotterdam | jq '.temperature')
          DESC=$(curl -s https://api.justinharing.nl/weather/Rotterdam | jq '.description')
          sed -i "s|Ask me about Dutch weather.*|Ask me about Dutch weather (currently $TEMP in Rotterdam with $DESC)|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update weather data"
          git push