name: update weather

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Fetch and update weather data
        run: |
          WEATHER=$(curl -s https://api.justinharing.nl/weather/Rotterdam)
          TEMP=$(echo "$WEATHER" | jq -r '.temperature' | tr '[:upper:]' '[:lower:]')
          DESC=$(echo "$WEATHER" | jq -r '.description' | tr '[:upper:]' '[:lower:]')

          # Replace only the placeholders in the README
          sed -i "s|{{TEMP_PLACEHOLDER}}|$TEMP|g" README.md
          sed -i "s|{{DESC_PLACEHOLDER}}|$DESC|g" README.md

      - name: Commit and push changes
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        run: |
          git add README.md
          git commit -m "Update weather data"
          git push
